### ISSUE TITLE
node-pngcrush does not support your node v12.6.0

### ISSUE THREAD

**Issue by callren** [xiangshouding/node-pngcrush#59]
node-pngcrush does not support your node v12.6.0

**Comment by dreamxyp** [comment]
npm install -g node-pngcrush

> node-pngcrush@1.0.1 install /Users/dreamxyp/.node_global/lib/node_modules/node-pngcrush
> node ./scripts/install.js

Downloading binary from https://github.com/xiangshouding/node-pngcrush/releases/download/v1.0.1/darwin-x64-72_binding.node
Cannot download "https://github.com/xiangshouding/node-pngcrush/releases/download/v1.0.1/darwin-x64-72_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
+ node-pngcrush@1.0.1
updated 2 packages in 7.017s
