### ISSUE TITLE
node-pngcrush does not support your node v0.11.13

### ISSUE THREAD

**Issue by sapjax** [xiangshouding/node-pngcrush#6]
[WARNI] node-pngcrush does not support your node v0.11.13, report it to https://github.com/xiangshouding/node-pngcrush/issues

**Comment by X-Bird** [comment]
[WARNI] node-pngcrush does not support your node v0.10.35, report it to https://github.com/xiangshouding/node-pngcrush/issues

**Comment by xiangshouding** [comment]
@X-Bird  这只是个意外，但肯定不是常态。

**Comment by X-Bird** [comment]
I gotcha!

**Comment by atian25** [comment]
[WARNI] node-pngcrush does not support your node v1.1.0, report it to https://github.com/xiangshouding/node-pngcrush/issues

考虑支持io.js吧~

**Comment by mhsun** [comment]
node-pngcrush does not support your node v0.12.0, report it to https://github.com/xiangshouding/node-pngcrush/issues

**Comment by xiangshouding** [comment]
@mhsun 最新的 fis 吗？不是得重装啊

**Comment by mhsun** [comment]
@xiangshouding 是最新的fis，然后我添加了v0.10的node就好了

**Comment by xiangshouding** [comment]
@mhsun 哪个系统，多少位？

**Comment by mhsun** [comment]
@xiangshouding ubuntu最新 64 bit

**Comment by xiangshouding** [comment]
@mhsun 嗯，这个比较难搞，我装台虚拟机看看怎么回事儿。
