### ISSUE TITLE
Newest release version not published to GitHub

### ISSUE THREAD

**Issue by nsturdivant** [xiangshouding/node-pngcrush#62]
The latest release version, `1.0.2`, is published to the public npm feed ([here](https://www.npmjs.com/package/node-pngcrush/v/1.0.2)). However, that same version doesn't seem to be published as a release in GitHub. Is the missing GitHub release intentional?

The missing release can manifest during an `npm install`. If, for whatever reason, the install command attempts to hit GitHub to download the necessary `.node` file, it doesn't find the file and throws a `404`:

```
...
> node-pngcrush@1.0.2 install Z:\a\agent\15\s\node_modules\node-pngcrush
> node ./scripts/install.js

Downloading binary from https://github.com/xiangshouding/node-pngcrush/releases/download/v1.0.2/win32-x64-48_binding.node
##[error]Cannot download "https://github.com/xiangshouding/node-pngcrush/releases/download/v1.0.2/win32-x64-48_binding.node": 
HTTP error 404 Not Found
Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 
      export HTTP_PROXY=http://example.com:1234
or configure npm proxy via
      npm config set proxy http://example.com:8080

...
```

Is this an oversight, or do I need to, say, use `npm-shrinkwrap` to pin version `1.0.1`?

> Note: I've created a similar issue for the `node-pngquant-native` package [here](https://github.com/xiangshouding/node-pngquant-native/issues/32).

**Comment by xiangshouding** [comment]
what is your node version？

Nick Sturdivant <notifications@github.com> 于 2020年5月26日周二 上午12:16写道：

**Comment by nsturdivant** [comment]
@xiangshouding Apologies for the delayed response. I've seen the installation errors using node version `6.14.1` as well as `8.12.0`. What was the resolution on this issue? User error 😉?
